(() => {
  const P = window.CTASProtocol;
  const S = { answers:{}, contributions:[], trail:[], history:[], current:null };
  const $ = id => document.getElementById(id);
  const qView=$('questionView'), rView=$('resultView'), nav=$('bottomNav');

  const LEVEL_NAMES={0:'No CTAS / documentation zero',1:'Resuscitation',2:'Emergent',3:'Urgent',4:'Less Urgent',5:'Non-Urgent'};
  const SOURCE={
    context:'Guide pp. 5–12', quick:'Guide p. 16 / pediatric p. 49', complaint:'Common prehospital presentations',
    resp:'Adult Table 1 / Pediatric Table 16', hemo:'Adult Table 2 / Pediatric Table 18', loc:'Adult Table 3 / Pediatric Table 20',
    temp:'Adult Table 4 / Pediatric Tables 21–22', pain:'Adult Table 5 / Pediatric Table 23', bleed:'Adult Table 6', moi:'Adult Table 7 / Pediatric Table 24',
    glucose:'Adult Table 8 / Pediatric Table 25', bp:'Adult Table 9', dehydration:'Adult Table 10', selected:'Adult Table 11', obstetric:'Adult Table 12', mental:'Adult Table 13',
    pediatric2:'Pediatric Tables 26–33'
  };

  function ageType(){ const a=Number(S.answers.age); return Number.isFinite(a) ? (a>=18?'adult':'pediatric') : null; }
  function dataset(){ return ageType()==='adult'?P.adultPresentations:P.pediatricPresentations; }
  function addContribution(level,label,ref,code){ if(!level && level!==0)return; const key=code||`${level}:${label}`; const i=S.contributions.findIndex(x=>x.key===key); const item={key,level:Number(level),label,ref}; if(i>=0)S.contributions[i]=item; else S.contributions.push(item); updateBest(); }
  function removePrefix(prefix){ S.contributions=S.contributions.filter(x=>!x.key.startsWith(prefix)); updateBest(); }
  function bestLevel(){ if(S.answers.obviouslyDead==='yes')return 0; if((S.answers.phase==='departure'||S.answers.phase==='current')&&S.answers.tor==='yes')return 0; if(!S.contributions.length)return null; return Math.min(...S.contributions.map(x=>x.level)); }
  function adjustedLevel(raw){ if(raw===null||raw===0)return raw; if((S.answers.phase==='departure'||S.answers.phase==='current') && S.answers.arrivalCTAS){ const arrival=Number(S.answers.arrivalCTAS); return Math.min(raw, Math.min(5,arrival+2)); } return raw; }
  function updateBest(){ const b=adjustedLevel(bestLevel()); $('currentBest').textContent=b===null?'CTAS —':`CTAS ${b}`; }
  function setAnswer(id,val,label){ S.answers[id]=val; const existing=S.trail.findIndex(x=>x.id===id); const item={id,label:label||String(val)}; if(existing>=0)S.trail[existing]=item; else S.trail.push(item); }
  function pushHistory(){ if(S.current)S.history.push(S.current); }
  function go(id){ S.current=id; renderQuestion(id); }
  function next(id){ pushHistory(); go(id); }
  function back(){ if(!S.history.length)return; const id=S.history.pop(); go(id); }

  function baseGroup(label){
    const rules=[
      [/cardiac arrest|ROSC/i,'Cardiac arrest / ROSC'],[/chest pain/i,'Chest pain'],[/hypertension/i,'High blood pressure'],[/dehydrat/i,'Dehydration'],[/syncope/i,'Syncope'],
      [/shortness of breath|respiratory distress|respiratory arrest|asthma|inadequate breathing/i,'Breathing problem'],[/foreign body obstruction|foreign body aspiration/i,'Airway foreign body'],[/stridor/i,'Stridor'],
      [/seizure/i,'Seizure'],[/CVA|stroke|extremity weakness/i,'Stroke / focal weakness'],[/headache/i,'Headache'],[/unconscious|unresponsive|altered consciousness|altered LOC/i,'Altered consciousness'],
      [/pregnancy ≥20 weeks|active labour|fetal|amniotic/i,'Pregnancy ≥20 weeks'],[/vaginal bleeding|menorrhagia|ectopic/i,'Vaginal bleeding / pregnancy problem'],
      [/burn/i,'Burn'],[/laceration|abrasion|contusion|puncture/i,'Wound / laceration'],[/fracture|extremity injury|sprain|strain|amputation/i,'Extremity / musculoskeletal injury'],[/major trauma|head injury|chest trauma|abdominal trauma|penetrating/i,'Trauma / injury'],
      [/vomiting blood|GI bleeding|rectal bleed/i,'GI bleeding'],[/abdominal pain/i,'Abdominal pain'],[/vomiting|diarrhea/i,'Vomiting / diarrhea'],[/constipation/i,'Constipation'],
      [/suicid|depression|self harm/i,'Depression / self-harm'],[/anxiety|situational crisis/i,'Anxiety / agitation'],[/violent|homicidal/i,'Violence / safety risk'],[/bizarre|psychosis|hallucination|delusion/i,'Psychosis / unusual behaviour'],[/insomnia/i,'Insomnia'],
      [/allergic|anaphylaxis/i,'Allergic reaction'],[/sore throat|upper respiratory|laryngitis/i,'Sore throat / URI'],[/epistaxis/i,'Nosebleed'],[/vision|eye|corneal|conjunctivitis/i,'Eye problem'],
      [/hypothermia|frostbite|cold injury/i,'Cold exposure'],[/bite/i,'Bite'],[/urinary|UTI|retention/i,'Urinary problem'],[/testicular|scrotal|priapism|paraphimosis/i,'Genitourinary problem'],
      [/infant|crying|feeding|floppy/i,'Infant behaviour / feeding'],[/abuse|assault|family violence/i,'Safety / abuse concern'],[/rash|cellulitis|skin/i,'Skin problem'],[/diabet|hypergly|hypogly/i,'Diabetes / glucose'],
      [/dressing change/i,'Dressing change']
    ];
    for(const [re,name] of rules)if(re.test(label))return name;
    return label.split(' – ')[0].split(' + ')[0].trim();
  }
  function groupsForCategory(category){
    const map=new Map();
    dataset().filter(x=>x.category===category).forEach(x=>{ const g=baseGroup(x.label); if(!map.has(g))map.set(g,[]); map.get(g).push(x); });
    return [...map.entries()].map(([name,items])=>({name,items}));
  }
  function selectedPresentation(){ return dataset().find(x=>x.id===S.answers.presentationId); }
  function isTraumaLike(){ const p=selectedPresentation(); if(!p)return false; return /trauma|injur|fracture|laceration|abrasion|contusion|amputation|fall|collision|penetrating|sprain|strain|burn/i.test(p.label) || ['Trauma','Musculoskeletal'].includes(p.category); }
  function isBleedingLike(){ const p=selectedPresentation(); return p && /bleed|hemorr|epistaxis|laceration|trauma|fracture|menorrhagia/i.test(p.label); }
  function isPainLikely(){ const p=selectedPresentation(); return p && /pain|injur|fracture|burn|laceration|headache|frostbite|bite|cramps|sprain|strain|abdomen|chest/i.test(p.label); }
  function adultGlucoseRelevant(){ const p=selectedPresentation(); return p && /diabet|hypergly|hypogly|altered|confusion|unconscious|seizure|weakness/i.test(p.label); }
  function adultBpRelevant(){ const p=selectedPresentation(); return p && /hypertension|chest pain|headache|cardiovascular/i.test(p.label+' '+p.category); }
  function dehydrationRelevant(){ const p=selectedPresentation(); return p && /dehydrat|vomit|diarrhea|weakness/i.test(p.label); }
  function mentalRelevant(){ const p=selectedPresentation(); return p && p.category==='Mental Health'; }
  function obstetricRelevant(){ const p=selectedPresentation(); return p && p.category==='Obstetrics/Gynecology' && /pregnan|labour|fetal|amniotic/i.test(p.label); }
  function pediatricSpecificRoute(){ const p=selectedPresentation(); if(!p)return null; const t=(p.label+' '+p.category).toLowerCase();
    if(/abuse|assault|family violence/.test(t))return 'welfare'; if(/disrupt|behaviour|psychiatry/.test(t))return 'disruptive'; if(/stridor/.test(t))return 'stridor'; if(/apne/.test(t))return 'apnea'; if(/inconsolable|irritable/.test(t))return 'crying'; if(/floppy|tone/.test(t))return 'floppy'; if(/gait|walking|limp/.test(t))return 'gait'; if(/congenital|metabolic|adrenal|shunt/.test(t))return 'congenital'; return null;
  }

  const questions={
    age:{title:'How old is the patient?',prompt:'Enter age in years. Use decimals for infants if needed.',help:'Adult CTAS is defined as ≥18 years; pediatric CTAS is <18 years.',source:SOURCE.context,type:'number',placeholder:'e.g. 42',min:0,max:120,next:()=> 'phase'},
    phase:{title:'Which CTAS are you assigning?',prompt:'Choose the point in the patient encounter.',source:SOURCE.context,type:'choices',options:[['arrival','Arrival CTAS'],['departure','Departure CTAS'],['current','En-route / current CTAS']],next:()=> (S.answers.phase==='arrival'?'obviouslyDead':'arrivalCTAS')},
    arrivalCTAS:{title:'What was the Arrival CTAS?',prompt:'This is used to apply the guide’s maximum two-level improvement rule.',source:'Rule #3 • Guide pp. 8–9',type:'choices',options:[['1','CTAS 1'],['2','CTAS 2'],['3','CTAS 3'],['4','CTAS 4'],['5','CTAS 5'],['','Unknown / not available']],next:()=> 'tor'},
    tor:{title:'Was a TOR received before transport?',prompt:'This only affects the departure/current documentation pathway.',source:'Rule #5 • Guide p. 10',type:'choices',options:[['yes','Yes — TOR before transport'],['no','No']],onAnswer:v=>{if(v==='yes')finish();},next:()=> 'obviouslyDead'},
    obviouslyDead:{title:'Is the patient obviously dead on arrival?',prompt:'Use the BLS PCS definition used by the guide.',source:'Rule #6 • Guide p. 10',type:'choices',options:[['yes','Yes'],['no','No']],onAnswer:v=>{if(v==='yes')finish();},next:()=> 'vsa'},
    vsa:{title:'Was the patient VSA / in cardiac arrest on arrival?',prompt:'This includes a patient who has since achieved ROSC.',source:'Rule #4 • Guide p. 9',type:'choices',options:[['yes','Yes — VSA / cardiac arrest'],['no','No']],onAnswer:v=>{removePrefix('special:vsa');if(v==='yes'){addContribution(1,'VSA on arrival / cardiac arrest; CTAS remains 1 after successful resuscitation',SOURCE.context,'special:vsa');finish();}},next:()=> 'quick'},
    quick:{title:()=>ageType()==='pediatric'?'First Look: does the child require immediate resuscitative intervention?':'Quick Look: does the patient require immediate resuscitative intervention?',prompt:'Use this only to identify an obvious CTAS 1 presentation.',help:'If the answer is no, the flow continues through presenting complaint and modifiers.',source:SOURCE.quick,type:'choices',options:[['yes','Yes — obvious CTAS 1'],['no','No / not obvious']],onAnswer:v=>{removePrefix('quick:');if(v==='yes'){addContribution(1,'Critical Quick Look / First Look',SOURCE.quick,'quick:1');finish();}},next:()=> 'category'},
    category:{title:'What system best matches the main complaint?',prompt:'Choose the closest CTAS presenting-complaint category.',source:'CEDIS / common prehospital presentations',type:'category',next:()=> 'complaintGroup'},
    complaintGroup:{title:'What is the main problem?',prompt:'Choose the closest complaint. The next question will clarify severity only if the guide has more than one version of it.',source:'Common prehospital presentations',type:'group',next:()=> 'presentation'},
    presentation:{title:'Which description best matches the patient?',prompt:'Select the closest protocol presentation.',source:'Common prehospital presentations',type:'presentation',onAnswer:()=>{const p=selectedPresentation();removePrefix('presentation:'); if(p)addContribution(p.level,p.label,`Guide p. ${p.page}`,'presentation:base');},next:()=>{const p=selectedPresentation(); if(p&&p.level===1){finish();return null;} return 'resp';}},
    resp:{title:'What is the patient’s respiratory status?',prompt:'Choose the highest applicable respiratory-distress description.',source:SOURCE.resp,type:'choices',options:()=> ageType()==='adult' ? [['severe','Severe distress / airway compromise','Fatigue, cyanosis, single-word or unable to speak, upper-airway obstruction, lethargy/confusion'],['moderate','Moderate distress','Increased work, phrases/clipped sentences, significant/worsening stridor with airway protected'],['mild','Mild / moderate','Dyspnea or tachypnea without obvious increased work; speaking sentences'],['none','No respiratory distress']] : [['severe','Severe distress / inadequate breathing'],['moderate','Moderate respiratory distress'],['mild','Mild respiratory distress'],['none','No respiratory distress']],onAnswer:v=>{removePrefix('resp:');const lv={severe:1,moderate:2,mild:3}[v];if(lv)addContribution(lv,`Respiratory modifier: ${v}`,SOURCE.resp,'resp:main');if(lv===1)finish();},next:()=> 'hemo'},
    hemo:{title:'How is perfusion / hemodynamic status?',prompt:'Choose the most acute description that applies.',source:SOURCE.hemo,type:'choices',options:()=> ageType()==='adult' ? [['shock','Shock / severe end-organ hypoperfusion','Marked pallor, cool/diaphoretic, weak/thready pulse, hypotension, major tachy/bradycardia, reduced LOC'],['compromise','Hemodynamic compromise / borderline perfusion','Pale, diaphoresis history, unexplained tachycardia, postural hypotension/faintness, suspected hypotension'],['abnormal','Vital signs at upper/lower end of normal for this patient'],['normal','Normal perfusion / vital signs']] : [['shock','Shock / severe perfusion problem'],['compromise','Hemodynamic compromise'],['volume','Volume depletion with abnormal vital signs'],['normal','Normal perfusion']],onAnswer:v=>{removePrefix('hemo:');const lv=ageType()==='adult'?{shock:1,compromise:2,abnormal:3}[v]:{shock:1,compromise:2,volume:3}[v];if(lv)addContribution(lv,`Hemodynamic modifier: ${v}`,SOURCE.hemo,'hemo:main');if(lv===1)finish();},next:()=> 'loc'},
    loc:{title:'What is the level of consciousness?',prompt:ageType()==='adult'?'Use GCS and clinical description.':'Use pediatric LOC / coma scale and clinical description.',source:SOURCE.loc,type:'choices',options:[['low','Unconscious / GCS or PCS 3–9'],['altered','Altered consciousness / GCS or PCS 10–13'],['normal','Normal / 14–15 or baseline']],onAnswer:v=>{removePrefix('loc:');const lv={low:1,altered:2}[v];if(lv)addContribution(lv,`Level of consciousness modifier: ${v}`,SOURCE.loc,'loc:main');if(lv===1)finish();},next:()=> ageType()==='adult'?'adultTempScreen':'pedTempScreen'},
    adultTempScreen:{title:'Is fever / suspected infection relevant?',prompt:'If there is an oral temperature ≥38.5°C, the adult temperature modifier may change acuity.',source:SOURCE.temp,type:'choices',options:[['yes','Yes — temp ≥38.5°C / suspected infection'],['no','No / not relevant'],['unknown','Temperature not available']],next:()=>S.answers.adultTempScreen==='yes'?'adultTempDetail':'painScreen'},
    adultTempDetail:{title:'Which fever description best fits?',prompt:'Choose the highest applicable description.',source:SOURCE.temp,type:'choices',options:[['immune','Immunocompromised','Neutropenia/suspected, chemotherapy or immunosuppressive drugs including steroids'],['septic','Looks septic','Evidence of infection + 3 SIRS criteria, or hemodynamic compromise, moderate respiratory distress, or altered LOC'],['unwell','Looks unwell','<3 SIRS criteria but ill-looking: flushed, lethargic, anxious or agitated'],['well','Looks well','Fever is the only positive SIRS criterion; comfortable and no distress']],onAnswer:v=>{removePrefix('temp:');const lv={immune:2,septic:2,unwell:3,well:4}[v];addContribution(lv,`Temperature modifier: ${v}`,SOURCE.temp,'temp:adult');},next:()=> 'painScreen'},
    pedTempScreen:{title:'Is temperature abnormal or fever a key feature?',prompt:'Pediatric temperature thresholds vary by age and appearance in the guide.',source:SOURCE.temp,type:'choices',options:[['yes','Yes'],['no','No / not relevant'],['unknown','Temperature not available']],next:()=>S.answers.pedTempScreen==='yes'?'pedTempDetail':'painScreen'},
    pedTempDetail:{title:'Which pediatric temperature situation best fits?',prompt:'Choose the closest protocol condition.',source:SOURCE.temp,type:'choices',options:[['infant','Infant <3 months with temperature <36°C or ≥38.5°C'],['toxic','Toxic / septic appearance with fever'],['older','Child 3–36 months with temperature >38.5°C'],['wellolder','Child ≥36 months, >38.5°C and non-toxic'],['other','Other / does not match these']],onAnswer:v=>{removePrefix('temp:ped');const lv={infant:2,toxic:2,older:3,wellolder:4}[v];if(lv)addContribution(lv,`Pediatric temperature modifier: ${v}`,SOURCE.temp,'temp:ped');},next:()=> 'painScreen'},
    painScreen:{title:'Is pain part of the presentation?',prompt:'Pain can modify acuity after higher-acuity physiological abnormalities have been considered.',source:SOURCE.pain,type:'choices',options:[['yes','Yes'],['no','No / not a meaningful feature']],next:()=>S.answers.painScreen==='yes'?'painSeverity':(isBleedingLike()&&ageType()==='adult'?'bleedRisk':(isTraumaLike()?'moi':'secondOrderStart'))},
    painSeverity:{title:'How severe is the pain?',prompt:'Use the patient’s reported 0–10 pain score.',source:SOURCE.pain,type:'choices',options:[['severe','Severe — 8 to 10/10'],['moderate','Moderate — 4 to 7/10'],['mild','Mild — 0 to 3/10']],next:()=>ageType()==='adult'?'painLocation':'pedPainChronic'},
    painLocation:{title:'Is the pain central or peripheral?',prompt:'Central pain originates in a body cavity/organ. Peripheral pain is skin, soft tissue, axial skeleton or superficial organs.',source:SOURCE.pain,type:'choices',options:[['central','Central'],['peripheral','Peripheral']],next:()=> 'painDuration'},
    painDuration:{title:'Is the pain acute or chronic?',prompt:'Acute means new onset; chronic means a recognized recurring/continuing pattern.',source:SOURCE.pain,type:'choices',options:[['acute','Acute'],['chronic','Chronic']],onAnswer:()=>{removePrefix('pain:');const s=S.answers.painSeverity,l=S.answers.painLocation,d=S.answers.painDuration;const map={severe:{central:{acute:2,chronic:3},peripheral:{acute:3,chronic:4}},moderate:{central:{acute:3,chronic:4},peripheral:{acute:4,chronic:5}},mild:{central:{acute:4,chronic:5},peripheral:{acute:5,chronic:5}}}; const lv=map?.[s]?.[l]?.[d];if(lv)addContribution(lv,`Adult pain modifier: ${s}, ${l}, ${d}`,SOURCE.pain,'pain:adult');},next:()=>isBleedingLike()?'bleedRisk':(isTraumaLike()?'moi':'secondOrderStart')},
    pedPainChronic:{title:'Is this chronic pain?',prompt:'The pediatric guide allows consideration of a lower level for chronic pain when appropriate.',source:SOURCE.pain,type:'choices',options:[['no','No — acute/new pain'],['yes','Yes — chronic/recurrent']],onAnswer:v=>{removePrefix('pain:ped');const base={severe:2,moderate:3,mild:4}[S.answers.painSeverity]; if(base){const lv=v==='yes'?Math.min(5,base+1):base; addContribution(lv,`Pediatric pain modifier: ${S.answers.painSeverity}${v==='yes'?', chronic':''}`,SOURCE.pain,'pain:ped');}},next:()=>isTraumaLike()?'moi':'secondOrderStart'},
    bleedRisk:{title:'Does the patient have increased bleeding risk?',prompt:'Congenital bleeding disorder, severe liver failure, or anticoagulant use.',source:SOURCE.bleed,type:'choices',options:[['yes','Yes'],['no','No']],next:()=>S.answers.bleedRisk==='yes'?'bleedSite':(isTraumaLike()?'moi':'secondOrderStart')},
    bleedSite:{title:'How significant is the bleeding site / pattern?',prompt:'Choose the higher-risk group if more than one applies.',source:SOURCE.bleed,type:'choices',options:[['major','High-risk / uncontrolled','Head/neck; chest/abdomen/pelvis/spine; massive vaginal hemorrhage; iliopsoas/hip; compartment; fracture/dislocation; deep laceration; any uncontrolled bleeding'],['minor','Moderate / minor','Epistaxis, mouth/gums, joints, menorrhagia, abrasion or superficial laceration']],onAnswer:v=>{removePrefix('bleed:');addContribution(v==='major'?2:3,`Bleeding-disorder modifier: ${v}`,SOURCE.bleed,'bleed:main');},next:()=>isTraumaLike()?'moi':'secondOrderStart'},
    moi:{title:'Does the mechanism meet the significant MOI table?',prompt:'Use the CTAS mechanism-of-injury criteria for this age group.',help:'Examples include qualifying ejection/rollover/intrusion/extrication, high-energy impact, specified falls, penetrating injury, and certain head/neck mechanisms.',source:SOURCE.moi,type:'choices',options:[['yes','Yes — significant MOI'],['no','No']],onAnswer:v=>{removePrefix('moi:');if(v==='yes')addContribution(2,'Significant mechanism of injury',SOURCE.moi,'moi:main');},next:()=> 'secondOrderStart'},
    glucoseScreen:{title:'Is glucose assessment relevant / available?',prompt:'Consider this for diabetes, altered consciousness, confusion, seizure, or similar presentations.',source:SOURCE.glucose,type:'choices',options:[['yes','Yes — I have a glucose value'],['no','No / not available']],next:()=>S.answers.glucoseScreen==='yes'?'glucoseValue':'secondOrderAfterGlucose'},
    glucoseValue:{title:'What is the blood glucose?',prompt:'Enter mmol/L.',source:SOURCE.glucose,type:'number',placeholder:'e.g. 2.8',min:0,max:60,step:'0.1',next:()=>{const g=Number(S.answers.glucoseValue);return (g<3||g>=18)?'glucoseSymptoms':'secondOrderAfterGlucose'}},
    glucoseSymptoms:{title:'Are associated symptoms present?',prompt:ageType()==='adult'?'Examples: confusion, seizure, diaphoresis, behavioural change, acute focal deficit; for high glucose: dyspnea, tachypnea, dehydration, thirst, weakness or polyuria.':'Examples: confusion, seizure/postictal state, diaphoresis, behavioural change; for high glucose: dyspnea, dehydration or weakness. Infant <1 year with glucose <3 mmol/L is included in the symptomatic CTAS 2 row.',source:SOURCE.glucose,type:'choices',options:[['yes','Yes'],['no','No']],onAnswer:v=>{removePrefix('glucose:');const g=Number(S.answers.glucoseValue);if(g<3||g>=18)addContribution(v==='yes'?2:3,`Blood glucose ${g} mmol/L with${v==='yes'?'':'out'} listed symptoms`,SOURCE.glucose,'glucose:main');},next:()=> 'secondOrderAfterGlucose'},
    bpValue:{title:'Enter the blood pressure',prompt:'Used for the adult hypertension second-order modifier.',source:SOURCE.bp,type:'bp',next:()=> 'bpSymptoms'},
    bpSymptoms:{title:'Are symptoms associated with the elevated blood pressure?',prompt:'Examples in the guide include headache, chest pain, shortness of breath or nausea.',source:SOURCE.bp,type:'choices',options:[['yes','Yes'],['no','No']],onAnswer:v=>{removePrefix('bp:');const sbp=Number(S.answers.sbp),dbp=Number(S.answers.dbp);let lv=null;if(sbp>=220||dbp>=130)lv=v==='yes'?2:3;else if((sbp>=200&&sbp<220)||(dbp>=110&&dbp<130))lv=v==='yes'?3:4;if(lv)addContribution(lv,`Hypertension modifier: ${sbp}/${dbp}, symptoms ${v}`,SOURCE.bp,'bp:main');},next:()=> dehydrationRelevant()?'dehydration':'adultSpecificStart'},
    dehydration:{title:'How dehydrated is the patient?',prompt:'Choose the closest adult dehydration description.',source:SOURCE.dehydration,type:'choices',options:[['severe','Severe','Marked volume loss + classic signs and shock'],['moderate','Moderate','Dry mucosa, tachycardia ± poor turgor / decreased urine output'],['mild','Mild','Stable vitals + thirst/concentrated urine + decreased intake/increased loss'],['potential','Potential','No dehydration signs but ongoing losses or difficulty tolerating oral fluids'],['none','No dehydration']],onAnswer:v=>{removePrefix('dehyd:');const lv={severe:1,moderate:2,mild:3,potential:4}[v];if(lv)addContribution(lv,`Dehydration modifier: ${v}`,SOURCE.dehydration,'dehyd:main');if(lv===1)finish();},next:()=> 'adultSpecificStart'},
    chestTear:{title:'Is the chest pain ripping or tearing?',prompt:'This is a selected second-order modifier for significant non-cardiac-feature chest pain.',source:SOURCE.selected,type:'choices',options:[['yes','Yes'],['no','No']],onAnswer:v=>{removePrefix('sel:chest');if(v==='yes')addContribution(2,'Other significant chest pain — ripping/tearing',SOURCE.selected,'sel:chest');},next:()=> 'finishCheck'},
    cvaTime:{title:'When did the stroke/CVA symptoms begin?',prompt:'Use the guide’s 3.5-hour threshold.',source:SOURCE.selected,type:'choices',options:[['early','Less than 3.5 hours'],['late','3.5 hours or more'],['resolved','Symptoms resolved']],onAnswer:v=>{removePrefix('sel:cva');addContribution(v==='early'?2:3,`CVA symptom onset: ${v}`,SOURCE.selected,'sel:cva');},next:()=> 'finishCheck'},
    dysphagia:{title:'How severe is the swallowing problem?',prompt:'Look for drooling, stridor, hoarseness or respiratory distress.',source:SOURCE.selected,type:'choices',options:[['distress','Drooling / stridor / hoarseness / dysphagia with concerning airway features'],['nodistress','Difficulty swallowing with no distress']],onAnswer:v=>{removePrefix('sel:dys');addContribution(v==='distress'?2:3,`Difficulty swallowing modifier: ${v}`,SOURCE.selected,'sel:dys');},next:()=> 'finishCheck'},
    deformity:{title:'Is there an obvious extremity deformity?',prompt:'An obvious upper or lower extremity deformity is a selected adult second-order modifier.',source:SOURCE.selected,type:'choices',options:[['yes','Yes'],['no','No']],onAnswer:v=>{removePrefix('sel:def');if(v==='yes')addContribution(3,'Extremity injury with obvious deformity',SOURCE.selected,'sel:def');},next:()=> 'finishCheck'},
    obstetric:{title:'Which ≥20-week obstetric condition applies?',prompt:'Choose the highest applicable condition.',source:SOURCE.obstetric,type:'choices',options:[['fetal','Presenting fetal parts / prolapsed cord'],['bleed','Third-trimester vaginal bleeding other than show'],['labour2','Active labour — contractions <2 min apart'],['movement','No fetal movement / no fetal heart sounds'],['htn','Complex hypertension ± headache/edema/abdominal pain'],['post','Post-delivery mother and infant'],['labour3','Active labour — contractions ≥2 min apart'],['fluid','Possible leaking amniotic fluid ≥24 h'],['none','None of these']],onAnswer:v=>{removePrefix('ob:');const lv={fetal:1,bleed:1,labour2:2,movement:2,htn:2,post:2,labour3:3,fluid:3}[v];if(lv)addContribution(lv,`Obstetric modifier: ${v}`,SOURCE.obstetric,'ob:main');if(lv===1)finish();},next:()=> 'finishCheck'},
    mental:{title:'Which mental-health risk description best fits?',prompt:'Choose the most acute applicable description.',source:SOURCE.mental,type:'mental',next:()=> 'finishCheck'},
    pediatric2:{title:'Which pediatric-specific modifier best fits?',prompt:'Choose the closest description. If none apply, select none.',source:SOURCE.pediatric2,type:'ped2',next:()=> 'finishCheck'},
    finishCheck:{title:'Ready to assign the CTAS level?',prompt:'The app has applied the selected presentation and all modifiers asked in this pathway.',help:'If there is another clinically applicable modifier that was not captured, use Back and choose the closest relevant pathway or rely on clinical judgment as the guide directs.',source:'Highest-acuity rule • Guide p. 24',type:'choices',options:[['finish','Show CTAS result']],onAnswer:()=>finish(),next:()=>null}
  };

  function secondOrderStart(){
    if(ageType()==='pediatric'){
      const p=selectedPresentation(); const t=(p?.label||'').toLowerCase();
      if(/diabet|altered|unconscious|confusion|seizure|letharg/.test(t))return 'glucoseScreen';
      const r=pediatricSpecificRoute(); return r?'pediatric2':'finishCheck';
    }
    if(adultGlucoseRelevant())return 'glucoseScreen';
    return secondOrderAfterGlucose();
  }
  function secondOrderAfterGlucose(){
    if(ageType()==='pediatric'){ return pediatricSpecificRoute()?'pediatric2':'finishCheck'; }
    if(adultBpRelevant())return 'bpValue';
    if(dehydrationRelevant())return 'dehydration';
    return adultSpecificStart();
  }
  function adultSpecificStart(){
    const p=selectedPresentation(); if(!p)return 'finishCheck'; const t=p.label.toLowerCase();
    if(obstetricRelevant())return 'obstetric';
    if(mentalRelevant())return 'mental';
    if(/chest pain/.test(t) && /non-cardiac|non cardiac/.test(t))return 'chestTear';
    if(/cva|stroke/.test(t))return 'cvaTime';
    if(/swallow|dysphagia|foreign body obstruction/.test(t))return 'dysphagia';
    if(/extremity|fracture/.test(t))return 'deformity';
    return 'finishCheck';
  }
  questions.secondOrderStart={next:secondOrderStart}; questions.secondOrderAfterGlucose={next:secondOrderAfterGlucose}; questions.adultSpecificStart={next:adultSpecificStart};

  function renderQuestion(id){
    if(['secondOrderStart','secondOrderAfterGlucose','adultSpecificStart'].includes(id)){ const nid=questions[id].next(); S.current=nid; return renderQuestion(nid); }
    const q=questions[id]; if(!q)return finish();
    qView.classList.remove('hidden'); rView.classList.add('hidden'); nav.classList.remove('hidden');
    $('backBtn').disabled=!S.history.length; $('sourceTag').textContent=q.source||''; $('questionTitle').textContent=typeof q.title==='function'?q.title():q.title; $('questionPrompt').textContent=typeof q.prompt==='function'?q.prompt():q.prompt||''; $('questionHelp').textContent=typeof q.help==='function'?q.help():q.help||''; $('stepLabel').textContent=`QUESTION ${Math.max(1,S.history.length+1)}`; $('progressBar').style.width=`${Math.min(92,6+S.history.length*5)}%`; updateBest();
    const area=$('answerArea'); area.innerHTML='';
    if(q.type==='choices'){ const wrap=document.createElement('div');wrap.className='answers'; const opts=typeof q.options==='function'?q.options():q.options; opts.forEach(o=>{const [val,label,sub]=o; const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`${esc(label)}${sub?`<span class="sub">${esc(sub)}</span>`:''}`;b.onclick=()=>answer(q,val,label);wrap.appendChild(b)});area.appendChild(wrap); }
    else if(q.type==='number'){ const box=document.createElement('div');box.className='field-card'; box.innerHTML=`<label>${esc(q.prompt||q.title)}</label><input id="numInput" inputmode="decimal" type="number" min="${q.min??''}" max="${q.max??''}" step="${q.step||'any'}" placeholder="${esc(q.placeholder||'')}" value="${esc(S.answers[id]??'')}"><button class="primary continue" id="numGo">Continue</button>`; area.appendChild(box); setTimeout(()=>{const inp=$('numInput');inp.focus();$('numGo').onclick=()=>{if(inp.value==='')return;answer(q,inp.value,inp.value)};inp.onkeydown=e=>{if(e.key==='Enter')$('numGo').click();};},0); }
    else if(q.type==='bp'){ const box=document.createElement('div');box.className='field-card';box.innerHTML=`<label>Systolic</label><input id="sbpIn" inputmode="numeric" type="number" placeholder="SBP" value="${esc(S.answers.sbp??'')}"><label style="margin-top:12px">Diastolic</label><input id="dbpIn" inputmode="numeric" type="number" placeholder="DBP" value="${esc(S.answers.dbp??'')}"><button class="primary continue" id="bpGo">Continue</button>`;area.appendChild(box);setTimeout(()=>{$('bpGo').onclick=()=>{const s=$('sbpIn').value,d=$('dbpIn').value;if(!s||!d)return;S.answers.sbp=s;S.answers.dbp=d;setAnswer('bpValue',`${s}/${d}`,`${s}/${d} mmHg`);const nid=q.next();next(nid);};},0); }
    else if(q.type==='category') renderCategories(q,area);
    else if(q.type==='group') renderGroups(q,area);
    else if(q.type==='presentation') renderPresentations(q,area);
    else if(q.type==='mental') renderMental(q,area);
    else if(q.type==='ped2') renderPed2(q,area);
    $('whyText').textContent=(q.help?`${typeof q.help==='function'?q.help():q.help} `:'')+`Source: ${q.source||'Prehospital CTAS guide'}.`;
  }

  function renderCategories(q,area){ const cats=[...new Set(dataset().map(x=>x.category))].sort(); const wrap=document.createElement('div');wrap.className='category-grid';cats.forEach(cat=>{const b=document.createElement('button');b.className='answer-btn';b.textContent=cat;b.onclick=()=>answer(q,cat,cat);wrap.appendChild(b)});area.appendChild(wrap); }
  function renderGroups(q,area){ const groups=groupsForCategory(S.answers.category); const wrap=document.createElement('div');wrap.className='answers';groups.forEach(g=>{const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`${esc(g.name)}<span class="sub">${g.items.length===1?'1 protocol presentation':`${g.items.length} protocol presentations — more clarification will follow`}</span>`;b.onclick=()=>{S.answers.group=g.name;setAnswer('complaintGroup',g.name,g.name);pushHistory(); if(g.items.length===1){S.answers.presentationId=g.items[0].id; setAnswer('presentation',g.items[0].id,g.items[0].label); const p=g.items[0];removePrefix('presentation:');addContribution(p.level,p.label,`Guide p. ${p.page}`,'presentation:base'); if(p.level===1)finish();else go('resp');} else go('presentation');};wrap.appendChild(b)});area.appendChild(wrap); }
  function renderPresentations(q,area){ const items=groupsForCategory(S.answers.category).find(g=>g.name===S.answers.group)?.items||[]; const search=document.createElement('div');search.className='search-wrap';search.innerHTML='<input id="presentFilter" placeholder="Filter these descriptions…">';area.appendChild(search); const wrap=document.createElement('div');wrap.className='answers';area.appendChild(wrap); const draw=term=>{wrap.innerHTML='';items.filter(x=>x.label.toLowerCase().includes(term.toLowerCase())).forEach(p=>{const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`${esc(p.label)}<span class="sub">Protocol candidate — modifiers can only increase acuity</span>`;b.onclick=()=>answer(q,p.id,p.label);wrap.appendChild(b)});};draw('');setTimeout(()=>{$('presentFilter').oninput=e=>draw(e.target.value);},0); }
  function renderMental(q,area){ const opts=[
    [1,'Imminent harm / specific violent plan, or uncontrolled bizarre behaviour'],[2,'Attempted suicide/clear plan, active intent, severe anxiety/agitation, acute psychosis, or uncertain flight/safety risk'],[3,'Suicidal ideation without plan, moderate anxiety/agitation/paranoia, violent ideation without plan, or abuse/high emotional stress'],[4,'Depressed without suicidal ideation, mild anxiety/agitation, acute insomnia'],[5,'Chronic hallucinations with mild symptoms, chronic insomnia, or chronic non-urgent bizarre behaviour']
  ]; const wrap=document.createElement('div');wrap.className='answers';opts.forEach(([lv,label])=>{const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`${esc(label)}<span class="sub">CTAS ${lv} mental-health modifier</span>`;b.onclick=()=>{removePrefix('mental:');addContribution(lv,label,SOURCE.mental,'mental:main');answer(q,String(lv),label);};wrap.appendChild(b)});area.appendChild(wrap); }
  function renderPed2(q,area){ const route=pediatricSpecificRoute(); const sets={
    welfare:[[1,'Conflict or unstable situation'],[2,'Risk of flight or ongoing abuse'],[3,'Physical or sexual assault'],[4,'History/signs of abuse or maltreatment']],
    disruptive:[[2,'Uncertain flight or safety risk / family distress'],[3,'Acute difficulties with others or environment'],[4,'Persistent problematic behaviour'],[5,'Chronic unchanged behaviour']],
    stridor:[[1,'Airway compromise'],[2,'Marked stridor'],[3,'Audible stridor']],
    apnea:[[1,'Apneic episode on presentation'],[2,'Recent spell with apnea/respiratory compromise'],[3,'History of spell consistent with apnea']],
    crying:[[2,'Inconsolable + abnormal vital signs'],[3,'Inconsolable + stable vital signs'],[4,'Irritable but consolable']],
    floppy:[[2,'No tone / unable to support head'],[3,'Limited / less than expected muscle tone']],
    gait:[[3,'Gait or limp problem with fever'],[4,'Walking with difficulty / caregiver identifies need for care']],
    congenital:[[2,'Rapid-deterioration protocol concern or vomiting/diarrhea with inherited metabolic disease, type 1 diabetes or adrenal insufficiency'],[3,'Caregiver identifies need for care'],[4,'Stable congenital disease with potential for problems']]
  }; const wrap=document.createElement('div');wrap.className='answers';(sets[route]||[]).forEach(([lv,label])=>{const b=document.createElement('button');b.className='answer-btn';b.innerHTML=`${esc(label)}<span class="sub">CTAS ${lv}</span>`;b.onclick=()=>{removePrefix('ped2:');addContribution(lv,label,SOURCE.pediatric2,'ped2:main');answer(q,String(lv),label);};wrap.appendChild(b)}); const none=document.createElement('button');none.className='answer-btn';none.textContent='None of these';none.onclick=()=>answer(q,'none','None of these');wrap.appendChild(none);area.appendChild(wrap); }

  function answer(q,val,label){ const id=S.current; setAnswer(id,val,label); if(q.onAnswer){q.onAnswer(val); if(rView.classList.contains('hidden')===false)return;} const nid=typeof q.next==='function'?q.next():q.next; if(nid)next(nid); }

  function finish(){
    let raw=bestLevel(); if(raw===null){raw=selectedPresentation()?.level??null;}
    const final=adjustedLevel(raw);
    qView.classList.add('hidden');rView.classList.remove('hidden');nav.classList.add('hidden');
    $('progressBar').style.width='100%';
    const badge=$('resultBadge'); badge.className='result-badge'; if(final!==null)badge.classList.add(`ctas-${final}`); badge.textContent=final===null?'?':final;
    $('resultTitle').textContent=final===null?'Clinical judgment required':(final===0?'CTAS 0 documentation':`CTAS ${final} — ${LEVEL_NAMES[final]}`);
    let summary=''; if(final===null)summary='The selected information does not resolve a CTAS level by itself. The guide directs paramedics to use the presenting complaint, all applicable modifiers, and clinical judgment.'; else if(final===0)summary='Special documentation rule selected. No standard CTAS 1–5 acuity is assigned for this pathway.'; else summary=`Highest-acuity applicable protocol result: CTAS ${final}.`;
    const rawB=bestLevel(); if(final!==null&&rawB!==null&&final!==rawB)summary+=` Rule #3 limited improvement from Arrival CTAS ${S.answers.arrivalCTAS}, changing the calculated ${rawB} to ${final}.`;
    $('resultSummary').textContent=summary;
    const reasons=$('rationaleList'); reasons.innerHTML=''; const sorted=[...S.contributions].sort((a,b)=>a.level-b.level); if(!sorted.length){const d=document.createElement('div');d.className='reason';d.textContent='No modifier contribution recorded.';reasons.appendChild(d);} else sorted.forEach(r=>{const d=document.createElement('div');d.className='reason';d.innerHTML=`<span class="pill">CTAS ${r.level}</span><strong>${esc(r.label)}</strong><span class="ref">${esc(r.ref||'')}</span>`;reasons.appendChild(d)});
    const trail=$('trailList');trail.innerHTML=''; S.trail.forEach(t=>{const d=document.createElement('div');d.className='trail-item';d.innerHTML=`<strong>${esc(prettyId(t.id))}:</strong> ${esc(t.label)}`;trail.appendChild(d)});
    $('resultCaution').textContent='Decision support based on the uploaded Ontario Prehospital CTAS Paramedic Guide Version 2.0 (2016). The guide states that Prehospital CTAS is an acuity indicator in the prehospital setting; current BLS/ALS standards, clinical assessment, local policy and medical direction still govern care.';
    updateBest();
  }
  function prettyId(id){return ({age:'Age',phase:'Assessment phase',arrivalCTAS:'Arrival CTAS',tor:'TOR',obviouslyDead:'Obviously dead',vsa:'VSA / arrest',quick:'Quick Look / First Look',category:'Category',complaintGroup:'Main complaint',presentation:'Presentation',resp:'Respiratory status',hemo:'Hemodynamics',loc:'Level of consciousness',adultTempScreen:'Fever/infection',adultTempDetail:'Adult temperature modifier',pedTempScreen:'Temperature relevance',pedTempDetail:'Pediatric temperature modifier',painScreen:'Pain present',painSeverity:'Pain severity',painLocation:'Pain location',painDuration:'Pain duration',pedPainChronic:'Chronic pain',bleedRisk:'Bleeding risk',bleedSite:'Bleeding severity/site',moi:'Mechanism of injury',glucoseScreen:'Glucose relevance',glucoseValue:'Blood glucose',glucoseSymptoms:'Glucose symptoms',bpValue:'Blood pressure',bpSymptoms:'BP symptoms',dehydration:'Dehydration',chestTear:'Chest pain tearing',cvaTime:'CVA onset',dysphagia:'Swallowing problem',deformity:'Extremity deformity',obstetric:'Obstetric modifier',mental:'Mental-health modifier',pediatric2:'Pediatric-specific modifier',finishCheck:'Finalize'})[id]||id;}
  function reset(){S.answers={};S.contributions=[];S.trail=[];S.history=[];S.current=null;qView.classList.remove('hidden');rView.classList.add('hidden');nav.classList.remove('hidden');go('age');}
  function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}

  $('backBtn').onclick=back; $('restartTop').onclick=()=>{if(confirm('Start a new assessment?'))reset();}; $('newAssessment').onclick=reset; $('whyBtn').onclick=()=>{$('whySheet').classList.remove('hidden');$('whySheet').setAttribute('aria-hidden','false');}; $('closeWhy').onclick=()=>{$('whySheet').classList.add('hidden');$('whySheet').setAttribute('aria-hidden','true');}; $('whySheet').onclick=e=>{if(e.target===$('whySheet'))$('closeWhy').click();};
  $('copySummary').onclick=async()=>{const level=adjustedLevel(bestLevel());const text=`CTAS ${level??'?'}${level!=null?` — ${LEVEL_NAMES[level]}`:''}\n${S.contributions.sort((a,b)=>a.level-b.level).map(r=>`CTAS ${r.level}: ${r.label}`).join('\n')}`;try{await navigator.clipboard.writeText(text);$('copySummary').textContent='Copied';setTimeout(()=>$('copySummary').textContent='Copy summary',1200);}catch{alert(text);}};
  reset();
})();
